name: supabase_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  camera: ^0.10.5+9
  chat_message_timestamp: ^0.0.1
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_secure_storage: ^9.0.0
  freezed_annotation: ^2.4.1
  grouped_list: ^5.1.2
  image_picker: ^1.0.7
  intl: ^0.19.0
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.1.2
  permission_handler: ^11.1.0
  riverpod_annotation: ^2.3.3
  supabase_flutter: ^2.3.4
  video_player: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  custom_lint: ^0.6.2
  json_serializable: ^6.7.1
  freezed: ^2.4.5

flutter:
  uses-material-design: true
